.\"
.\" nic.1 - the *roff document processor source for the nic manual
.\"
.TH nic 1 "2019-01-15" "theoldmoon0602"
.ds dc \fIdc\fP
.ds Dc \fIdc\fP
.SH NAME
nic \- Nishida calculator
.SH SYNOPSIS
nic
.SH DESCRIPTION
.PP
.IR nic
is Nishida calculator. This can calculate addition, subtraction, multiplication and division.
.SH Examples

.TP
.B > 1+1
2
.TP
.B > 50*2*3-50-2*5/2-11*3
212
.TP
.B > 3/2
1.5
.TP
.B > 1/0
inf

.SH Easter Eggs
.TP
.B When you use 1130 to calculate
Nic celebrates the special day of the Nishida.
.TP
.B When you calculate 21 times 21
Nic remember you the greatest teacher.
.TP
.B In a probability of 1%
Nishida-kun mistake to calculate...
